services:
  postgres:
    image: postgres:17

    container_name: eventflow-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    
    ports:
      - "2506:5432"
    
    volumes:
      - postgres-eventflow-data:/var/lib/postgresql/data  

volumes:
  postgres-eventflow-data: